### ISSUE TITLE
Inconsistent IDs in provider/vehicle.json

### ISSUE THREAD

**Issue by ezmckinn** [openmobilityfoundation/mobility-data-specification#623] opened 2021-02-02 17:23 UTC
Inconsistent $id definitions within the object with the address: #/properties/data/properties, in vehicle.json in the provider API. From lines 319-350, the $id field reads `#/definitions/vehicle/properties/...`. Based on the other items within the object (lines 351-377), it appears these fields should be `#/properties/vehicle/properties/...`

`    "properties": {
              "provider_name": {
                "$id": "#/definitions/vehicle/properties/provider_name",
                "$ref": "#/definitions/string",
                "description": "The public-facing name of the Provider"
              },
              "provider_id": {
                "$id": "#/definitions/vehicle/properties/provider_id",
                "$ref": "#/definitions/uuid",
                "description": "The UUID for the Provider, unique within MDS"
              },
              "device_id": {
                "$id": "#/definitions/vehicle/properties/device_id",
                "$ref": "#/definitions/uuid",
                "description": "A unique device ID in UUID format"
              },
              "vehicle_id": {
                "$id": "#/definitions/vehicle/properties/vehicle_id",
                "$ref": "#/definitions/string",
                "description": "The Vehicle Identification Number visible on the vehicle itself"
              },
              "vehicle_type": {
                "$id": "#/definitions/vehicle/properties/vehicle_type",
                "$ref": "#/definitions/vehicle_type",
                "description": "The type of vehicle"
              },
              "propulsion_types": {
                "$id": "#/definitions/vehicle/properties/propulsion_types",
                "$ref": "#/definitions/propulsion_types",
                "description": "The type of propulsion; allows multiple values",
                "minItems": 1
              },`

**Expected behavior**
Consistent $id fields within a givn object.

**Additional context**

Not sure if this is a feature or a bug. Can submit PR to fix if it's a bug.

**Comment by thekaveman** [comment] 2021-02-03 18:41
Not a bug, this is an artifact of how the schemas are generated and that we (re)use a common structure for vehicles for many of the schemas. That definition comes from here: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/schema/common.py#L30 and is merged into e.g. the `vehicles.json` here: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/schema/provider.py#L60

@ezmckinn is this causing an issue when you attempt to validate?

**Comment by ezmckinn** [comment] 2021-02-05 00:19
Hi there - thanks for the reply. No, I have not attempted to use it yet. I
was just reading through the documentation for my own understanding and was
confused. It was addressed during today's City Services WG call. Thanks!

Emmett

**Comment by schnuerle** [comment] 2021-02-11 14:16
Thanks for the question @ezmckinn and for the detailed help @thekaveman.

**Closed by schnuerle** 2021-02-11 14:16 UTC
Labels: JSON Schema, Provider
